blank_issues_enabled: false
contact_links:
  - name: âœ¨ Feature Requests & ğŸ› Bug Reports
    url: https://demo.okta.com
    about: Something missing from demo.okta that you'd like to see? Submit a feature or enhancement request. Something consistently wrong? Specifically something not behaving the way you'd expect? File a bug report. All through demo.okta.com
  - name: ğŸ’¬ Connect with #demo-okta
    url: https://okta.slack.com/archives/CE676UAUS
    about: Feedback and communications are important. Come give us some ğŸ’™ on Slack.