blank_issues_enabled: false
contact_links:
  - name: âœ¨ Feature Request
    url: https://form.asana.com/?k=ztfbuea-mrKtg78y2aoYkA&d=10114792544943
    about: Something missing from demo.okta that you'd like to see? Submit a feature or enhancement request
  - name: ğŸ› Bug Report
    url: https://form.asana.com/?k=kanxmU6S4hsgLwave7nyzQ&d=10114792544943
    about: Something consistently wrong? Specifically something not behaving the way you'd expect? File a bug report. 
  - name: ğŸ’¬ Connect with #demo-okta
    url: https://okta.slack.com/archives/CE676UAUS
    about: Feedback and communications are imortant. Come give us some ğŸ’™ on Slack.